d = {"one":1,"two":2,"three":3}
d2 = {k:v for k,v in d.items()}
print(d2)
d3 = {k:v for k,v in d.items() if v%2!=0}
print(d3)
print(str(d2))
i = d3.items()
print(type(i))
print(i)
print(d)
print(max(d))
print(min(d))
print(len(d))
print(dict(d))
d.clear()
print(d)
k = d2.keys()
print(k)
v = d2.values()
print(v)
print(type(k))
print(type(v))
print(d2.get("two"))
print(d2.get("three",100))
print(d2.get("two222",111111))
print(d2["two"])
print(d2["two22"])